AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM template

Resources:
  IssueProcessorLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: Provided
      Runtime: provided
      CodeUri: .build/lambda/IssueProcessorLambda/lambda.zip
      Environment:
        Variables:
          LOG_LEVEL: debug
      Events:
        SQSEvent:
            Type: SQS
            Properties:
              Queue: arn:aws:sqs:us-west-2:855037544458:blog-issue-updates
              BatchSize: 10
              Enabled: true

  BlogMediaBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: eneko-blog-media
      AccessControl: PublicRead
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
            AllowedOrigins:
              - '*'
            ExposedHeaders:
              - Date
            Id: myCORSRuleId1
            MaxAge: '3600'
