name: Issue Updated

on:
  issues:
    types: [edited, labeled, unlabeled]

jobs:
  generateSocialPreview:
    runs-on: macos-latest
    if: ${{ github.event.issue.user.login == github.repository_owner }} # only owner issues
    steps:
      - name: Check-out
        uses: actions/checkout@master
      - name: Copy Fonts
        run: |
          mkdir -p ~/Library/Fonts/
          cp Fonts/* ~/Library/Fonts/
      - name: Generate Preview
        run: |
          swift run socialpreview ${{ toJSON(github.event.issue) }}
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Copy to S3
        run: |
          aws s3 cp issue-25.png s3://eneko-blog-media/social-preview/issue-25.png --acl public-read

  pushToSNS:
    needs: generateSocialPreview
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.user.login == github.repository_owner }} # only owner issues
    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - uses: isbang/sqs-action@v0.1.1
        with:
          sqs-url: https://sqs.us-west-2.amazonaws.com/855037544458/blog-issue-updates
          message: ${{ toJSON(github) }}
